### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by lazaroff** [kokole/SteamItemDropIdler#11]
Can I use steam with SIDI at the same time if SIDI launched in sandboxie?

**Comment by gmmanonymus111** [comment]
Nah, it seems you won't get any items when you run multiple instances of the program (it's working with steam opened & program run in sandboxie)

Edit: I might not wait enough, running a couple of bots, it drops for me now... Sorry for the above text

**Comment by kokole** [comment]
I don't think that's possible, but you could always try. The problem was that SIDI was randomly closing if Steam was open or Steam folder wasn't renamed.
