### ISSUE TITLE
Add new game and fix program :)

### ISSUE THREAD

**Issue by Tadebu** [kokole/SteamItemDropIdler#16]
i suggest to add http://store.steampowered.com/app/270450/
that game have 40 min drop every 40 min if you played some modgame

**Comment by Novoxudobosor** [comment]
Как на счет H1Z1: King of the Kill?

**Comment by Novoxudobosor** [comment]
PLAYERUNKNOWN'S BATTLEGROUNDS?

**Comment by Novoxudobosor** [comment]
Robot Roller-Derby Disco Dodgeball?
