### ISSUE TITLE
Is there a way to read automatic generate an 2fa?

### ISSUE THREAD

**Issue by Schknheit** [kokole/SteamItemDropIdler#19]
Trading would be easier

**Comment by titoncio** [comment]
this is alreadly implemented.

**Comment by Schknheit** [comment]
Not really, everytime when i try to automatize everything on a batch file and the user has the mobile authenticator, everytime i launch via batch file, it asks for the mobile code.

**Comment by Schknheit** [comment]
Eu peguei rar do n3tcode mas, quando abro a solução no visual studio ele da um conflito ao dizer que está usando c enquanto algo está em c++

**Comment by titoncio** [comment]
Don't clone if you don't know how to use.
https://github.com/Ne3tCode/SteamItemDropIdler/releases/tag/v2.04.1

**Comment by titoncio** [comment]
Also, portuguese is your main language? I can help you in portuguese cause i'm brazilian.

**Comment by Schknheit** [comment]
Cara, eu coloquei o codigo do SDA no .exe mas ele não gera o 2FA. Copiei o shared secret do .ma do SDA e coloquei no test.secret, apaguei a primeira linha e colei como no .ma, mas mesmo assim não gerou.
