### ISSUE TITLE
CS:GO support

### ISSUE THREAD

**Issue by kokole** [kokole/SteamItemDropIdler#2]

**Comment by GreYzZ** [comment]
@kokole 
When do you add the support for CS:GO?

**Comment by kokole** [comment]
I don't know. Working on other stuff atm

**Comment by GreYzZ** [comment]
@kokole 
But it's possible?

**Comment by kokole** [comment]
Yes it is.

**Comment by GreYzZ** [comment]
@kokole 
To add this GameID would be great atm due the new Operation drops :D

**Comment by kokole** [comment]
Stopped development.

**Comment by GreYzZ** [comment]
@kokole why is the delelopment stopped? I really liked the programm
