### ISSUE TITLE
Family Library Sharing 

### ISSUE THREAD

**Issue by Quki5** [kokole/SteamItemDropIdler#20]
The account has access to the game through Family Library Sharing, but I get it: 

You are not subscribed to this app. Trying to add a free license... 
Failed to add a free license. You do not own this game
Press enter to exit...

**Comment by gmmanonymus111** [comment]
I think you can't get any drops if you don't own the game (e.g. you have it through family sharing), so it's not possible to get drops

**Comment by Quki5** [comment]
No, I get what I need

**Comment by gmmanonymus111** [comment]
My bad, it IS possible to get drops that way, but i don't know what you needed.

**Comment by igrobers** [comment]
i have got the  same problem. Do you know the solution?

**Comment by Quki5** [comment]
kokole can help. But he's not answering

**Comment by titoncio** [comment]
Try to copy the folder from steam userdata, because need share the library in "computer SIDI" 

I don´t know exactly what files are needed, i can see this in about 1~2 weeks cause i'm without my PC

**Comment by gmmanonymus111** [comment]
You only need the config.vdf from `*steam*/config/` folder, just copy the "_**AuthorizedDevice" {*somedata*}**_ part to `*steamitemdropidler*/config/config.vdf`
Keep in mind, you might not be able to play any steam games online while your bot is using family sharing

**Comment by Gonzaka** [comment]
gmmanonymus111 " just copy the "AuthorizedDevice" {somedata} part to *steamitemdropidler*/config/config.vdf"
It don't work.
