### ISSUE TITLE
Linux compatible 

### ISSUE THREAD

**Issue by efinskiy** [kokole/SteamItemDropIdler#21]
Hello.
Please add linux compatible version of sidi.
(wine is shit)
Thank you for understanding.

**Comment by dimon222** [comment]
I think it might be enough to just recompile for Linux. I don't really see much windows related code here.

**Comment by CallyyllaC** [comment]
I've noticed some windows specific code, but I am not familiar enough with c++ to do anything with it. Although Linux compatibility would be nice, wine never works.
