### ISSUE TITLE
Closed!

### ISSUE THREAD

**Issue by JetPony** [kokole/SteamItemDropIdler#22]
Error 0x80000419

**Comment by Novoxudobosor** [comment]
Похоже что эти ребята все. RUST тоже перестал дропать после релиза.
Разработчик последний раз отписывался больше года назад, похоже эта тема себя изжила странно что еще нет аналогов этой программы.

**Comment by gmmanonymus111** [comment]
JetPony, would you like to tell me where did you find that Valve returned the confirmations? I didn't found anything regarding this, and the program seems to work fine for me (as of march 2nd).

**Comment by Appolosiom** [comment]
@gmmanonymus111 There is no source that Valve returned the confirmations. My own tests reveal that this is not true. Could you please confirm you are running appid: 440 and receiving no issues as of March 2nd?

**Comment by gmmanonymus111** [comment]
@Appolosiom The appid is 440 ofc, othervise I'd not get any items. By working fine, i meant i've got some items, but not as much as it used to be (i've ran into similar issues before, but it went back to normal after a few weeks). In the meantime, I've read that valve banned a lot of idle bots, so you may be right, and this is the end of SIDI

**Comment by Appolosiom** [comment]
@gmmanonymus111 I would not believe everything you read, no idle bots were banned recently. Most are in the same position of JetPony, and are unable to even compile the source, let alone fix it. I have experienced the same issue as you describe. Would you be willing to confer on a more private platform?

**Comment by JetPony** [comment]
The problem solved, Issue closed.

**Comment by Appolosiom** [comment]
@JetPony Did you perhaps mean 0x80001049 not 0x80000419? There is no enumerated emsg for 419 ;-)

**Comment by gmmanonymus111** [comment]
@Appolosiom that supposed to be 0x80000419, I can't figure out how these messages are converted to enums or vice-versa, any ideas?

**Comment by DixieF** [comment]
@gmmanonymus111  0x80000419 ==  0x419 == 1049. Which is k_EMsgGCUpdateItemSchema

**Comment by gmmanonymus111** [comment]
@DixieF Thank you, now I understand!

**Comment by MikeLund** [comment]
@JetPony How did you fix it? TF2 is still broken for me.

**Comment by gmmanonymus111** [comment]
So, it's been a few weeks, and the problem didn't go away as it used to be. I'm assuming you really need to accept items before a new drop (correct me if I'm wrong). Possible fix could be sending a 'SetSingleItemPosition' message to place it, but to do that, you need to know the itemID (so you need your inventory data). Does anyone know how to get inventory data?

**Comment by Appolosiom** [comment]
@gmmanonymus111 The itemID is already exposed for you. Unfortunately until I fix my own issues with updating I cannot help further with yours.
