### ISSUE TITLE
Current program state

### ISSUE THREAD

**Issue by gmmanonymus111** [kokole/SteamItemDropIdler#23]
Hello there!
It seems the other issue is "closed", although there were no direct answer/solution posted.
My question is wether SIDI work for you or (like me) you do not get any drops?
I've tried placing new items in my inventory one by one, but it doesn't seem to update until SIDI is closed (so you will not get an inventory update) Is there a GC message which forces your inventory to update?
Also, is there any way to test sent/received GC messages besides NetHook?

Any answer/feedback would be greatly appreciated and I hope my test might be useful for someone.

Until then, I'll try different workarounds in my freetime, I'll update once I've found something.

**Comment by Appolosiom** [comment]
"I've tried placing new items in my inventory one by one, but it doesn't seem to update until SIDI is closed "
No problems here doing that.

**Comment by gmmanonymus111** [comment]
@Appolosiom In that case, could you tell me how you send GC messages? The problem might be I'm sending it incorrectly

**Comment by Appolosiom** [comment]
SendMessage( uint32 unMsgType, const void *pubData, uint32 cubData )

**Comment by DixieF** [comment]
I haven't seen no weapon drop since the GC patch.
It seems that the biggest problem is that VAC is required to be enabled to get the drops now. And VAC isn't that easy to be fooled.

Correct me if I'm wrong.

**Comment by gmmanonymus111** [comment]
I meant how do you make the protobuf message that is sent to the GC

**Comment by Appolosiom** [comment]
You construct the message, and send it using SendMessage, I'm not exactly sure what you are trying to ask, which proto are you trying to send?
Either of you getting 0x1976 responses since the gc patch?

**Comment by gmmanonymus111** [comment]
@Appolosiom Of course I know what function sends the message, and I got it working (sort of), is there any way to check if the message goes through GC successfully?, e.g. ` SendMessage(0x8000044C, response, sizeof(response));` where response[] is `0x19 0xf6 0xf2 0x91 0x01 0x00 0x00 0x00 0x4c 0x00 0x00 0x00 0x00 0x00 0x00 0x00`. I know for sure the content of the message is currect, but it doesn't seem to update my inventory
And yes, I got 0x1976 responses

@DixieF According to `steamGameServer->BSecure();` VAC is enabled on the 'local server', but it might be it is not enough to fool the drop system

**Comment by Appolosiom** [comment]
@gmmanonymus111 Sorry I should probably be more specific. You are still receiving 0x1976 responses after the initial one you receive while initing the game server?

**Comment by gmmanonymus111** [comment]
@Appolosiom No, there is no other 0x1976 responses besides the first one, but if I remember right, I used to get it a lot.

Back on topic: I think accepting items is still unnecessary, something else was changed by Valve, I suspect GC Hello/Welcome messages (before this "update" when I launched SIDI, my bot was playing tf2 when viewed in steam client, but showed up only online when viewed in steam mobile app. Now the bot plays tf2 on both clients.)

**Comment by Appolosiom** [comment]
@gmmanonymus111 
The GC Hello message was removed a long time ago, the welcome message has no effect on the result when updated to the correct version.
I was subtly attempting to put you on the -right- topic ;-)

**Comment by gmmanonymus111** [comment]
@Appolosiom  Well, I'm completely lost now, what should be the right topic, if not the GC messages? I'm starting to guess you managed to fix the program, but do not want others to achieve the same (so easily :P)

**Comment by Appolosiom** [comment]
@gmmanonymus111 The right topic is what is missing, what has changed, when it changed and what did it change to (if anything). The gc messages you have been referring to have had no changes in a long time.
I have not fixed the problem, but have spent time on the problem, and the program itself, implementing features such as sorting and updating it to the newest steam client. I am wary of being any more specific in such a public place.

**Comment by DixieF** [comment]
@Appolosiom it appears that they haven't changed anything, just reverted the drop system to its pre-2015 state as described here http://www.teamfortress.com/post.php?id=11105

@gmmanonymus111 I bet it is not enough.

**Comment by Appolosiom** [comment]
@DixieF If you say so.

**Comment by somethingthatsnotquitethere** [comment]
@Appolosiom  I see what you're doing there. You are more than specific for people whose attention you are trying to avoid.
