### ISSUE TITLE
KF2 event tickets issue

### ISSUE THREAD

**Issue by spamer4437** [kokole/SteamItemDropIdler#24]
Cannot launch correctly on virtual machine. But works correctly on my PC. KF2 now (while can farm tickets):
[*] Logged in
[*] You are not subscribed to this app. Trying to add a free license...
[!] Failed to add a free license. You do not own this game
[*] Logged off
How to fix it?

**Comment by SeRi0uS007** [comment]
Можешь смело ставить closed!
Тут соседние темы 2-3 годичной давности без ответа висят.

Если на ПК все работает, то дело ну уж никак не в этом софте.

**Comment by spamer4437** [comment]
sorry, was wrong ID. =)
