### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by theFreeWall** [kokole/SteamItemDropIdler#26]

**Comment by SeRi0uS007** [comment]
CS:GO doesn't use TriggerItemDrop().
All multiplayer Valve games use their own GameCoordinator's.
Personally I have no idea what you needs to be done to simulate a game on the server...

**Comment by theFreeWall** [comment]
> All multiplayer Valve games use their own GameCoordinator's.

Team Fortress 2
AppID: 440
Drop List Definition: 0

But we could get tf2 item drops before with this.

**Comment by SeRi0uS007** [comment]
TeamFortress 2 code doesn't use this parameter (you can see it in source). And the number 0 is used purely as a stub.
Below is an excerpt from the official SteamWorks documentation:

`SteamItemDef_t | int32 | Types of items in your game are identified by a 32-bit "item definition number". Valid definition numbers are between 1 and 999999999; numbers less than or equal to zero are invalid, and numbers greater than or equal to one billion (1x10^9) are reserved for internal Steam use.`
