### ISSUE TITLE
About SteamItemDropIdler's How it works

### ISSUE THREAD

**Issue by WiLuX-Source** [kokole/SteamItemDropIdler#27]
So I researched this program and saw 4 or 5 video.And I'm still not sure will it cause me a ban or not.
I read the comments in the steamgifts.com and saw the JustArchi he's a knowledgeable person.

Well If it is really cause a ban(I'm not Sure yet.) Which kind of ban can i get?
I don't care Vac bans to be honest I'm already banned from csgo and i still use my account as a normal person.But Can A Ban Go Further than this If I idle a item with this program?

**Comment by WiLuX-Source** [comment]
Btw this is my first time asking a question in github.So apologize for it,If i posted this somewhere wrong :/

**Comment by dimon222** [comment]
I'm afraid nobody knows answer for this. This is some new area.
