### ISSUE TITLE
How to run automatically?

### ISSUE THREAD

**Issue by BigBOSSo** [kokole/SteamItemDropIdler#8]
I have more than 100 accounts, there is no fun to enter Username, Password, game code each time. Can you tell me how to run automatically through batch file and so forth?

**Comment by kokole** [comment]
https://github.com/kokole/SteamItemDropIdler/wiki/How-to-use-(command-line)

**Comment by SuperSandro2000** [comment]
The command doesn't work for me. It still prompts me to enter the AppID.

**Comment by kokole** [comment]
It might be a bug, but I'm not updating this version anymore. Try Nephrite's version: https://github.com/Ne3tCode/SteamItemDropIdler
