### ISSUE TITLE
Definition to Primal Carnage: Extinction please.

### ISSUE THREAD

**Issue by AcperPlayGames** [kokole/SteamItemDropIdler#9]
Please give definition code to Primal Carnage: Extinction 

AppId: 321360

Game: http://store.steampowered.com/app/321360

Download Game (.exe):  http://www48.zippyshare.com/v/g4w9jOzH/file.html

Me steam: http://steamcommunity.com/id/acperplaygames/

**Comment by kokole** [comment]
This game doesn't use the SteamInventory API.
